name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install ngrok
        run: |
          sudo apt update
          sudo apt install unzip
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          chmod +x ngrok

      - name: Authenticate ngrok
        run: ./ngrok authtoken $NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Install Telnet
        run: |
          sudo apt update
          sudo apt install telnet -y

      - name: Install iperf
        run: |
          sudo apt install iperf -y

      - name: Allow SSH and Telnet Ports
        run: |
          sudo ufw allow 22/tcp
          sudo ufw allow 23/tcp
          sudo ufw enable

      # You may need additional steps here for configuring your Ubuntu environment as needed.

      - name: Create SSH Tunnel
        run: ./ngrok tcp 22 &

      - name: Create Telnet Tunnel
        run: ./ngrok tcp 23
